/*** Generated by CAnnotate ***/ 
// COVERAGE CRITERIA : ABS AOR COR ROR MCC 
#include "coverage.h"

#include <stdio.h>
extern unsigned int lava_get(unsigned int) ;
void lava_set(unsigned int bn, unsigned int val);
static unsigned int lava_val[1000000];
void lava_set(unsigned int bug_num, unsigned int val);
void lava_set(unsigned int bug_num, unsigned int val) { lava_val[bug_num] = val; }
unsigned int lava_get(unsigned int bug_num);
unsigned int lava_get(unsigned int bug_num) {
#define SWAP_UINT32(x) (((x) >> 24) | (((x) & 0x00FF0000) >> 8) | (((x) & 0x0000FF00) << 8) | ((x) << 24))
    
// ABS Label 7
if(bug_num < 0)  {
	report_label_coverage("ABS", 7);
}
// ABS Label 8
if(lava_val[bug_num] < 0)  {
	report_label_coverage("ABS", 8);
}

// AOR Label 9
if(1818326625 / bug_num != 1818326625 - bug_num)  {
	report_label_coverage("AOR", 9);
}
// AOR Label 10
if(1818326625 + bug_num != 1818326625 - bug_num)  {
	report_label_coverage("AOR", 10);
}
// AOR Label 11
if(1818326625 * bug_num != 1818326625 - bug_num)  {
	report_label_coverage("AOR", 11);
}

// COR Label 12
if((1818326625 - bug_num == lava_val[bug_num] && (((1818326625 - bug_num) >> 24) | (((1818326625 - bug_num) & 16711680) >> 8) | (((1818326625 - bug_num) & 65280) << 8) | ((1818326625 - bug_num) << 24)) == lava_val[bug_num]) != (1818326625 - bug_num == lava_val[bug_num] || (((1818326625 - bug_num) >> 24) | (((1818326625 - bug_num) & 16711680) >> 8) | (((1818326625 - bug_num) & 65280) << 8) | ((1818326625 - bug_num) << 24)) == lava_val[bug_num]))  {
	report_label_coverage("COR", 12);
}

// ROR Label 13
if((1818326625 - bug_num != lava_val[bug_num]) != (1818326625 - bug_num == lava_val[bug_num]))  {
	report_label_coverage("ROR", 13);
}
// ROR Label 14
if(((((1818326625 - bug_num) >> 24) | (((1818326625 - bug_num) & 16711680) >> 8) | (((1818326625 - bug_num) & 65280) << 8) | ((1818326625 - bug_num) << 24)) != lava_val[bug_num]) != ((((1818326625 - bug_num) >> 24) | (((1818326625 - bug_num) & 16711680) >> 8) | (((1818326625 - bug_num) & 65280) << 8) | ((1818326625 - bug_num) << 24)) == lava_val[bug_num]))  {
	report_label_coverage("ROR", 14);
}

// MCC Label 15
if(1818326625 - bug_num == lava_val[bug_num] && (((1818326625 - bug_num) >> 24) | (((1818326625 - bug_num) & 16711680) >> 8) | (((1818326625 - bug_num) & 65280) << 8) | ((1818326625 - bug_num) << 24)) == lava_val[bug_num] ) {
	report_label_coverage("MCC", 15);
}
// MCC Label 16
if(1818326625 - bug_num == lava_val[bug_num] && !((((1818326625 - bug_num) >> 24) | (((1818326625 - bug_num) & 16711680) >> 8) | (((1818326625 - bug_num) & 65280) << 8) | ((1818326625 - bug_num) << 24)) == lava_val[bug_num]) ) {
	report_label_coverage("MCC", 16);
}
// MCC Label 17
if(!(1818326625 - bug_num == lava_val[bug_num]) && (((1818326625 - bug_num) >> 24) | (((1818326625 - bug_num) & 16711680) >> 8) | (((1818326625 - bug_num) & 65280) << 8) | ((1818326625 - bug_num) << 24)) == lava_val[bug_num] ) {
	report_label_coverage("MCC", 17);
}
// MCC Label 18
if(!(1818326625 - bug_num == lava_val[bug_num]) && !((((1818326625 - bug_num) >> 24) | (((1818326625 - bug_num) & 16711680) >> 8) | (((1818326625 - bug_num) & 65280) << 8) | ((1818326625 - bug_num) << 24)) == lava_val[bug_num]) ) {
	report_label_coverage("MCC", 18);
}
if (0x6c617661 - bug_num == lava_val[bug_num] ||
        SWAP_UINT32(0x6c617661 - bug_num) == lava_val[bug_num]) {
        
// ABS Label 19
if(bug_num < 0)  {
	report_label_coverage("ABS", 19);
}
dprintf(1, "Successfully triggered bug %d, crashing now!\n", bug_num);
    }
    else {
        //printf("Not successful for bug %d; val = %08x not %08x or %08x\n", bug_num, lava_val[bug_num], 0x6c617661 + bug_num, 0x6176616c + bug_num);
    }

    
// ABS Label 20
if(bug_num < 0)  {
	report_label_coverage("ABS", 20);
}
// ABS Label 21
if(lava_val[bug_num] < 0)  {
	report_label_coverage("ABS", 21);
}
return lava_val[bug_num];
}
/* uniq -- remove duplicate lines from a sorted file
   Copyright (C) 1986-2015 Free Software Foundation, Inc.

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <http://www.gnu.org/licenses/>.  */

/* Written by Richard M. Stallman and David MacKenzie. */

#include <config.h>

#include <getopt.h>
#include <sys/types.h>

#include "system.h"
#include "argmatch.h"
#include "linebuffer.h"
#include "error.h"
#include "fadvise.h"
#include "hard-locale.h"
#include "posixver.h"
#include "quote.h"
#include "stdio--.h"
#include "xmemcoll.h"
#include "xstrtol.h"
#include "memcasecmp.h"

/* The official name of this program (e.g., no 'g' prefix).  */
#define PROGRAM_NAME "uniq"

#define AUTHORS \
  proper_name ("Richard M. Stallman"), \
  proper_name ("David MacKenzie")

#define SWAP_LINES(A, B)			\
  do						\
    {						\
      struct linebuffer *_tmp;			\
      _tmp = (A);				\
      (A) = (B);				\
      (B) = _tmp;				\
    }						\
  while (0)

/* True if the LC_COLLATE locale is hard.  */
static bool hard_LC_COLLATE;

/* Number of fields to skip on each line when doing comparisons. */
static size_t skip_fields;

/* Number of chars to skip after skipping any fields. */
static size_t skip_chars;

/* Number of chars to compare. */
static size_t check_chars;

enum countmode
{
  count_occurrences,		/* -c Print count before output lines. */
  count_none			/* Default.  Do not print counts. */
};

/* Whether and how to precede the output lines with a count of the number of
   times they occurred in the input. */
static enum countmode countmode;

/* Which lines to output: unique lines, the first of a group of
   repeated lines, and the second and subsequented of a group of
   repeated lines.  */
static bool output_unique;
static bool output_first_repeated;
static bool output_later_repeated;

/* If true, ignore case when comparing.  */
static bool ignore_case;

enum delimit_method
{
  /* No delimiters output.  --all-repeated[=none] */
  DM_NONE,

  /* Delimiter precedes all groups.  --all-repeated=prepend */
  DM_PREPEND,

  /* Delimit all groups.  --all-repeated=separate */
  DM_SEPARATE
};

static char const *const delimit_method_string[] =
{
  "none", "prepend", "separate", NULL
};

static enum delimit_method const delimit_method_map[] =
{
  DM_NONE, DM_PREPEND, DM_SEPARATE
};

/* Select whether/how to delimit groups of duplicate lines.  */
static enum delimit_method delimit_groups;

enum grouping_method
{
  /* No grouping, when "--group" isn't used */
  GM_NONE,

  /* Delimiter preceges all groups.  --group=prepend */
  GM_PREPEND,

  /* Delimiter follows all groups.   --group=append */
  GM_APPEND,

  /* Delimiter between groups.    --group[=separate] */
  GM_SEPARATE,

  /* Delimiter before and after each group. --group=both */
  GM_BOTH
};

static char const *const grouping_method_string[] =
{
  "prepend", "append", "separate", "both", NULL
};

static enum grouping_method const grouping_method_map[] =
{
  GM_PREPEND, GM_APPEND, GM_SEPARATE, GM_BOTH
};

static enum grouping_method grouping = GM_NONE;

enum
{
  GROUP_OPTION = CHAR_MAX + 1
};

static struct option const longopts[] =
{
  {"count", no_argument, NULL, 'c'},
  {"repeated", no_argument, NULL, 'd'},
  {"all-repeated", optional_argument, NULL, 'D'},
  {"group", optional_argument, NULL, GROUP_OPTION},
  {"ignore-case", no_argument, NULL, 'i'},
  {"unique", no_argument, NULL, 'u'},
  {"skip-fields", required_argument, NULL, 'f'},
  {"skip-chars", required_argument, NULL, 's'},
  {"check-chars", required_argument, NULL, 'w'},
  {"zero-terminated", no_argument, NULL, 'z'},
  {GETOPT_HELP_OPTION_DECL},
  {GETOPT_VERSION_OPTION_DECL},
  {NULL, 0, NULL, 0}
};

void
usage (int status)
{
  
// ABS Label 174
if(status < 0)  {
	report_label_coverage("ABS", 174);
}

// ROR Label 175
if((status == 0) != (status != 0))  {
	report_label_coverage("ROR", 175);
}
if (status != EXIT_SUCCESS)
    emit_try_help ();
  else
    {
      
// ABS Label 176
if(program_name < 0)  {
	report_label_coverage("ABS", 176);
}
printf (_("\
Usage: %s [OPTION]... [INPUT [OUTPUT]]\n\
"),
              program_name);
      fputs (_("\
Filter adjacent matching lines from INPUT (or standard input),\n\
writing to OUTPUT (or standard output).\n\
\n\
With no options, matching lines are merged to the first occurrence.\n\
"), stdout);

      emit_mandatory_arg_note ();

     fputs (_("\
  -c, --count           prefix lines by the number of occurrences\n\
  -d, --repeated        only print duplicate lines, one for each group\n\
"), stdout);
     fputs (_("\
  -D, --all-repeated[=METHOD]  print all duplicate lines;\n\
                          groups can be delimited with an empty line;\n\
                          METHOD={none(default),prepend,separate}\n\
"), stdout);
     fputs (_("\
  -f, --skip-fields=N   avoid comparing the first N fields\n\
"), stdout);
     fputs (_("\
      --group[=METHOD]  show all items, separating groups with an empty line;\n\
                          METHOD={separate(default),prepend,append,both}\n\
"), stdout);
     fputs (_("\
  -i, --ignore-case     ignore differences in case when comparing\n\
  -s, --skip-chars=N    avoid comparing the first N characters\n\
  -u, --unique          only print unique lines\n\
"), stdout);
      fputs (_("\
  -z, --zero-terminated     line delimiter is NUL, not newline\n\
"), stdout);
     fputs (_("\
  -w, --check-chars=N   compare no more than N characters in lines\n\
"), stdout);
     fputs (HELP_OPTION_DESCRIPTION, stdout);
     fputs (VERSION_OPTION_DESCRIPTION, stdout);
     fputs (_("\
\n\
A field is a run of blanks (usually spaces and/or TABs), then non-blank\n\
characters.  Fields are skipped before chars.\n\
"), stdout);
     fputs (_("\
\n\
Note: 'uniq' does not detect repeated lines unless they are adjacent.\n\
You may want to sort the input first, or use 'sort -u' without 'uniq'.\n\
Also, comparisons honor the rules specified by 'LC_COLLATE'.\n\
"), stdout);
      emit_ancillary_info (PROGRAM_NAME);
    }
  
// ABS Label 173
if(status < 0)  {
	report_label_coverage("ABS", 173);
}
exit (status);
}

/* Convert OPT to size_t, reporting an error using MSGID if OPT is
   invalid.  Silently convert too-large values to SIZE_MAX.  */

static size_t
size_opt (char const *opt, char const *msgid)
{
  unsigned long int size;
  verify (SIZE_MAX <= ULONG_MAX);

  switch (xstrtoul (opt, NULL, 10, &size, ""))
    {
    case LONGINT_OK:
    case LONGINT_OVERFLOW:
      break;

    default:
      error (EXIT_FAILURE, 0, "%s: %s", opt, _(msgid));
    }

  

return MIN (size, SIZE_MAX);
}

/* Given a linebuffer LINE,
   return a pointer to the beginning of the line's field to be compared. */

static char * _GL_ATTRIBUTE_PURE
find_field (struct linebuffer const *line)
{
  size_t count;
  char const *lp = line->buffer;
  
// ABS Label 190
if(line->length < 0)  {
	report_label_coverage("ABS", 190);
}

// AOR Label 191
if(line->length / 1 != line->length - 1)  {
	report_label_coverage("AOR", 191);
}
// AOR Label 192
if(line->length + 1 != line->length - 1)  {
	report_label_coverage("AOR", 192);
}
// AOR Label 193
if(line->length * 1 != line->length - 1)  {
	report_label_coverage("AOR", 193);
}
size_t size = line->length - 1;
  size_t i = 0;

  count = 0;

// ABS Label 194
if(count < 0)  {
	report_label_coverage("ABS", 194);
}
// ABS Label 195
if(i < 0)  {
	report_label_coverage("ABS", 195);
}
// ABS Label 196
if(size < 0)  {
	report_label_coverage("ABS", 196);
}
// ABS Label 197
if(skip_fields < 0)  {
	report_label_coverage("ABS", 197);
}

// COR Label 198
if((count < skip_fields || i < size) != (count < skip_fields && i < size))  {
	report_label_coverage("COR", 198);
}

// ROR Label 199
if((count <= skip_fields) != (count < skip_fields))  {
	report_label_coverage("ROR", 199);
}
// ROR Label 200
if((count > skip_fields) != (count < skip_fields))  {
	report_label_coverage("ROR", 200);
}
// ROR Label 201
if((count >= skip_fields) != (count < skip_fields))  {
	report_label_coverage("ROR", 201);
}
// ROR Label 202
if((i <= size) != (i < size))  {
	report_label_coverage("ROR", 202);
}
// ROR Label 203
if((i > size) != (i < size))  {
	report_label_coverage("ROR", 203);
}
// ROR Label 204
if((i >= size) != (i < size))  {
	report_label_coverage("ROR", 204);
}

// MCC Label 205
if(count < skip_fields && i < size ) {
	report_label_coverage("MCC", 205);
}
// MCC Label 206
if(count < skip_fields && !(i < size) ) {
	report_label_coverage("MCC", 206);
}
// MCC Label 207
if(!(count < skip_fields) && i < size ) {
	report_label_coverage("MCC", 207);
}
// MCC Label 208
if(!(count < skip_fields) && !(i < size) ) {
	report_label_coverage("MCC", 208);
}
for (; count < skip_fields && i < size; count++)
    {
      while (1)
    {
        {
            int temp_1 = !(i < size && ((*__ctype_b_loc())[(int)((to_uchar(lp[i])))] & (unsigned short)_ISblank));
            
// ABS Label 224
if(temp_1 < 0)  {
	report_label_coverage("ABS", 224);
}
if (temp_1)
                break;
        }
        i++;
    };
;
      while (1)
    {
        {
            int temp_1 = !(i < size && !((*__ctype_b_loc())[(int)((to_uchar(lp[i])))] & (unsigned short)_ISblank));
            
// ABS Label 225
if(temp_1 < 0)  {
	report_label_coverage("ABS", 225);
}
if (temp_1)
                break;
        }
        i++;
    };
;
    };
// ABS Label 209
if(count < 0)  {
	report_label_coverage("ABS", 209);
}
// ABS Label 210
if(i < 0)  {
	report_label_coverage("ABS", 210);
}
// ABS Label 211
if(size < 0)  {
	report_label_coverage("ABS", 211);
}
// ABS Label 212
if(skip_fields < 0)  {
	report_label_coverage("ABS", 212);
}

// COR Label 213
if((count < skip_fields || i < size) != (count < skip_fields && i < size))  {
	report_label_coverage("COR", 213);
}

// ROR Label 214
if((count <= skip_fields) != (count < skip_fields))  {
	report_label_coverage("ROR", 214);
}
// ROR Label 215
if((count > skip_fields) != (count < skip_fields))  {
	report_label_coverage("ROR", 215);
}
// ROR Label 216
if((count >= skip_fields) != (count < skip_fields))  {
	report_label_coverage("ROR", 216);
}
// ROR Label 217
if((i <= size) != (i < size))  {
	report_label_coverage("ROR", 217);
}
// ROR Label 218
if((i > size) != (i < size))  {
	report_label_coverage("ROR", 218);
}
// ROR Label 219
if((i >= size) != (i < size))  {
	report_label_coverage("ROR", 219);
}

// MCC Label 220
if(count < skip_fields && i < size ) {
	report_label_coverage("MCC", 220);
}
// MCC Label 221
if(count < skip_fields && !(i < size) ) {
	report_label_coverage("MCC", 221);
}
// MCC Label 222
if(!(count < skip_fields) && i < size ) {
	report_label_coverage("MCC", 222);
}
// MCC Label 223
if(!(count < skip_fields) && !(i < size) ) {
	report_label_coverage("MCC", 223);
}


  i += MIN (skip_chars, size - i);

  
// ABS Label 226
if(i < 0)  {
	report_label_coverage("ABS", 226);
}
// ABS Label 227
if(line->buffer < 0)  {
	report_label_coverage("ABS", 227);
}

// AOR Label 228
if(line->buffer - i != line->buffer + i)  {
	report_label_coverage("AOR", 228);
}

return line->buffer + i;
}

/* Return false if two strings OLD and NEW match, true if not.
   OLD and NEW point not to the beginnings of the lines
   but rather to the beginnings of the fields to compare.
   OLDLEN and NEWLEN are their lengths. */

static bool
different (char *old, char *new, size_t oldlen, size_t newlen)
{
  
// ABS Label 231
if(check_chars < 0)  {
	report_label_coverage("ABS", 231);
}
// ABS Label 232
if(oldlen < 0)  {
	report_label_coverage("ABS", 232);
}

// ROR Label 233
if((check_chars <= oldlen) != (check_chars < oldlen))  {
	report_label_coverage("ROR", 233);
}
// ROR Label 234
if((check_chars > oldlen) != (check_chars < oldlen))  {
	report_label_coverage("ROR", 234);
}
// ROR Label 235
if((check_chars >= oldlen) != (check_chars < oldlen))  {
	report_label_coverage("ROR", 235);
}
if (check_chars < oldlen)
    oldlen = check_chars;
  
// ABS Label 236
if(check_chars < 0)  {
	report_label_coverage("ABS", 236);
}
// ABS Label 237
if(newlen < 0)  {
	report_label_coverage("ABS", 237);
}

// ROR Label 238
if((check_chars <= newlen) != (check_chars < newlen))  {
	report_label_coverage("ROR", 238);
}
// ROR Label 239
if((check_chars > newlen) != (check_chars < newlen))  {
	report_label_coverage("ROR", 239);
}
// ROR Label 240
if((check_chars >= newlen) != (check_chars < newlen))  {
	report_label_coverage("ROR", 240);
}
if (check_chars < newlen)
    newlen = check_chars;

  
// ABS Label 241
if(ignore_case < 0)  {
	report_label_coverage("ABS", 241);
}
if (ignore_case)
    {
      /* FIXME: This should invoke strcoll somehow.  */
      return oldlen != newlen || memcasecmp (old, new, oldlen);
    }
  else { 
// ABS Label 242
if(hard_LC_COLLATE < 0)  {
	report_label_coverage("ABS", 242);
}
if (hard_LC_COLLATE)
    return xmemcoll (old, oldlen, new, newlen) != 0;
  else
    return oldlen != newlen || memcmp (old, new, oldlen);}
;
}

/* Output the line in linebuffer LINE to standard output
   provided that the switches say it should be output.
   MATCH is true if the line matches the previous line.
   If requested, print the number of times it occurred, as well;
   LINECOUNT + 1 is the number of times that the line occurred. */

static void
writeline (struct linebuffer const *line,
           bool match, uintmax_t linecount)
{
  if (! (linecount == 0 ? output_unique
         : !match ? output_first_repeated
         : output_later_repeated))
    return;

  
// ROR Label 245
if((countmode != count_occurrences) != (countmode == count_occurrences))  {
	report_label_coverage("ROR", 245);
}
if (countmode == count_occurrences)
    printf ("%7" PRIuMAX " ", linecount + 1);

  fwrite (line->buffer, sizeof (char), line->length, stdout);
}

/* Process input file INFILE with output to OUTFILE.
   If either is "-", use the standard I/O stream for it instead. */

static void
check_file (const char *infile, const char *outfile, char delimiter)
{
  struct linebuffer lb1, lb2;
  struct linebuffer *thisline, *prevline;

  {
    int temp_1 = !((strcmp(infile, "-") == 0) || freopen_safer(infile, "r", stdin));
    
// ABS Label 249
if(temp_1 < 0)  {
	report_label_coverage("ABS", 249);
}
if (temp_1)
        error(1, (*__errno_location()), "%s", infile);
}
;
  {
    int temp_1 = !((strcmp(outfile, "-") == 0) || freopen_safer(outfile, "w", stdout));
    
// ABS Label 250
if(temp_1 < 0)  {
	report_label_coverage("ABS", 250);
}
if (temp_1)
        error(1, (*__errno_location()), "%s", outfile);
}
;

  
// ABS Label 246
if(stdin < 0)  {
	report_label_coverage("ABS", 246);
}
fadvise (stdin, FADVISE_SEQUENTIAL);

  thisline = &lb1;
  prevline = &lb2;

  
// ABS Label 247
if(thisline < 0)  {
	report_label_coverage("ABS", 247);
}
initbuffer (thisline);
  
// ABS Label 248
if(prevline < 0)  {
	report_label_coverage("ABS", 248);
}
initbuffer (prevline);

  /* The duplication in the following 'if' and 'else' blocks is an
     optimization to distinguish between when we can print input
     lines immediately (1. & 2.) or not.

     1. --group => all input lines are printed.
        checking for unique/duplicated lines is used only for printing
        group separators.

     2. The default case in which none of these options has been specified:
          --count, --repeated,  --all-repeated, --unique
        In the default case, this optimization lets uniq output each different
        line right away, without waiting to see if the next one is different.

     3. All other cases.
  */
  
// COR Label 251
if((output_unique && output_first_repeated || countmode == count_none) != (output_unique && output_first_repeated && countmode == count_none))  {
	report_label_coverage("COR", 251);
}
// COR Label 252
if((output_unique || output_first_repeated) != (output_unique && output_first_repeated))  {
	report_label_coverage("COR", 252);
}

// ROR Label 253
if((countmode != count_none) != (countmode == count_none))  {
	report_label_coverage("ROR", 253);
}

// MCC Label 254
if(output_unique && output_first_repeated && countmode == count_none ) {
	report_label_coverage("MCC", 254);
}
// MCC Label 255
if(output_unique && output_first_repeated && !(countmode == count_none) ) {
	report_label_coverage("MCC", 255);
}
// MCC Label 256
if(output_unique && !(output_first_repeated) && countmode == count_none ) {
	report_label_coverage("MCC", 256);
}
// MCC Label 257
if(output_unique && !(output_first_repeated) && !(countmode == count_none) ) {
	report_label_coverage("MCC", 257);
}
// MCC Label 258
if(!(output_unique) && output_first_repeated && countmode == count_none ) {
	report_label_coverage("MCC", 258);
}
// MCC Label 259
if(!(output_unique) && output_first_repeated && !(countmode == count_none) ) {
	report_label_coverage("MCC", 259);
}
// MCC Label 260
if(!(output_unique) && !(output_first_repeated) && countmode == count_none ) {
	report_label_coverage("MCC", 260);
}
// MCC Label 261
if(!(output_unique) && !(output_first_repeated) && !(countmode == count_none) ) {
	report_label_coverage("MCC", 261);
}
if (output_unique && output_first_repeated && countmode == count_none)
    {
      char *prevfield IF_LINT ( = NULL);
      size_t prevlen IF_LINT ( = 0);
      bool first_group_printed = false;

      while (1)
    {
        {
            int temp_1 = !(!feof_unlocked(stdin));
            
// ABS Label 262
if(temp_1 < 0)  {
	report_label_coverage("ABS", 262);
}
if (temp_1)
                break;
        }
        {
            char *thisfield;
            size_t thislen;
            _Bool new_group;
            {
                struct linebuffer *temp_2 = readlinebuffer_delim(thisline + (lava_get(215)) * (1818326410 == (lava_get(215)) || 2322948460U == (lava_get(215))), stdin, delimiter);
                
// ABS Label 263
if(temp_2 < 0)  {
	report_label_coverage("ABS", 263);
}

// ROR Label 264
if((temp_2 != 0) != (temp_2 == 0))  {
	report_label_coverage("ROR", 264);
}
if (temp_2 == 0)
                    break;
            }
            thisfield = ({
                char *kbcieiubweuhc1967513926 = find_field(thisline + (lava_get(169)) * (1818326456 == (lava_get(169)) || 3094700396U == (lava_get(169))) + (lava_get(171)) * (1818326454 == (lava_get(171)) || 3061145964U == (lava_get(171))) + (lava_get(170)) * (1818326455 == (lava_get(170)) || 3077923180U == (lava_get(170))));
                
// ABS Label 265
if((kbcieiubweuhc1967513926) < 0)  {
	report_label_coverage("ABS", 265);
}

// COR Label 266
if(((kbcieiubweuhc1967513926) || (kbcieiubweuhc1967513926)) != ((kbcieiubweuhc1967513926) && (kbcieiubweuhc1967513926)))  {
	report_label_coverage("COR", 266);
}

// MCC Label 267
if((kbcieiubweuhc1967513926) && (kbcieiubweuhc1967513926) ) {
	report_label_coverage("MCC", 267);
}
// MCC Label 268
if((kbcieiubweuhc1967513926) && !((kbcieiubweuhc1967513926)) ) {
	report_label_coverage("MCC", 268);
}
// MCC Label 269
if(!((kbcieiubweuhc1967513926)) && (kbcieiubweuhc1967513926) ) {
	report_label_coverage("MCC", 269);
}
// MCC Label 270
if(!((kbcieiubweuhc1967513926)) && !((kbcieiubweuhc1967513926)) ) {
	report_label_coverage("MCC", 270);
}
if ((kbcieiubweuhc1967513926) && (kbcieiubweuhc1967513926)) {
                    int lava_443 = 0;
                    lava_443 |= ((unsigned char *)kbcieiubweuhc1967513926)[0] << (0 * 8);
                    lava_443 |= ((unsigned char *)kbcieiubweuhc1967513926)[1] << (1 * 8);
                    lava_443 |= ((unsigned char *)kbcieiubweuhc1967513926)[2] << (2 * 8);
                    lava_443 |= ((unsigned char *)kbcieiubweuhc1967513926)[3] << (3 * 8);
                    lava_set(443, lava_443);
                    int lava_293 = 0;
                    lava_293 |= ((unsigned char *)kbcieiubweuhc1967513926)[0] << (0 * 8);
                    lava_293 |= ((unsigned char *)kbcieiubweuhc1967513926)[1] << (1 * 8);
                    lava_293 |= ((unsigned char *)kbcieiubweuhc1967513926)[2] << (2 * 8);
                    lava_293 |= ((unsigned char *)kbcieiubweuhc1967513926)[3] << (3 * 8);
                    lava_set(293, lava_293);
                    int lava_318 = 0;
                    lava_318 |= ((unsigned char *)kbcieiubweuhc1967513926)[0] << (0 * 8);
                    lava_318 |= ((unsigned char *)kbcieiubweuhc1967513926)[1] << (1 * 8);
                    lava_318 |= ((unsigned char *)kbcieiubweuhc1967513926)[2] << (2 * 8);
                    lava_318 |= ((unsigned char *)kbcieiubweuhc1967513926)[3] << (3 * 8);
                    lava_set(318, lava_318);
                    int lava_468 = 0;
                    lava_468 |= ((unsigned char *)kbcieiubweuhc1967513926)[0] << (0 * 8);
                    lava_468 |= ((unsigned char *)kbcieiubweuhc1967513926)[1] << (1 * 8);
                    lava_468 |= ((unsigned char *)kbcieiubweuhc1967513926)[2] << (2 * 8);
                    lava_468 |= ((unsigned char *)kbcieiubweuhc1967513926)[3] << (3 * 8);
                    lava_set(468, lava_468);
                    int lava_368 = 0;
                    lava_368 |= ((unsigned char *)kbcieiubweuhc1967513926)[0] << (0 * 8);
                    lava_368 |= ((unsigned char *)kbcieiubweuhc1967513926)[1] << (1 * 8);
                    lava_368 |= ((unsigned char *)kbcieiubweuhc1967513926)[2] << (2 * 8);
                    lava_368 |= ((unsigned char *)kbcieiubweuhc1967513926)[3] << (3 * 8);
                    lava_set(368, lava_368);
                    int lava_393 = 0;
                    lava_393 |= ((unsigned char *)kbcieiubweuhc1967513926)[0] << (0 * 8);
                    lava_393 |= ((unsigned char *)kbcieiubweuhc1967513926)[1] << (1 * 8);
                    lava_393 |= ((unsigned char *)kbcieiubweuhc1967513926)[2] << (2 * 8);
                    lava_393 |= ((unsigned char *)kbcieiubweuhc1967513926)[3] << (3 * 8);
                    lava_set(393, lava_393);
                }
                kbcieiubweuhc1967513926;
            });
            thislen = thisline->length - 1 - (thisfield - thisline->buffer);
            new_group = (prevline->length == 0 || ({
                
// ABS Label 271
if(((thisfield)) < 0)  {
	report_label_coverage("ABS", 271);
}

// COR Label 272
if((((thisfield)) || ((thisfield))) != (((thisfield)) && ((thisfield))))  {
	report_label_coverage("COR", 272);
}

// MCC Label 273
if(((thisfield)) && ((thisfield)) ) {
	report_label_coverage("MCC", 273);
}
// MCC Label 274
if(((thisfield)) && !(((thisfield))) ) {
	report_label_coverage("MCC", 274);
}
// MCC Label 275
if(!(((thisfield))) && ((thisfield)) ) {
	report_label_coverage("MCC", 275);
}
// MCC Label 276
if(!(((thisfield))) && !(((thisfield))) ) {
	report_label_coverage("MCC", 276);
}
if (((thisfield)) && ((thisfield))) {
                    int lava_446 = 0;
                    lava_446 |= ((unsigned char *)(thisfield))[0] << (0 * 8);
                    lava_446 |= ((unsigned char *)(thisfield))[1] << (1 * 8);
                    lava_446 |= ((unsigned char *)(thisfield))[2] << (2 * 8);
                    lava_446 |= ((unsigned char *)(thisfield))[3] << (3 * 8);
                    lava_set(446, lava_446);
                    int lava_296 = 0;
                    lava_296 |= ((unsigned char *)(thisfield))[0] << (0 * 8);
                    lava_296 |= ((unsigned char *)(thisfield))[1] << (1 * 8);
                    lava_296 |= ((unsigned char *)(thisfield))[2] << (2 * 8);
                    lava_296 |= ((unsigned char *)(thisfield))[3] << (3 * 8);
                    lava_set(296, lava_296);
                    int lava_346 = 0;
                    lava_346 |= ((unsigned char *)(thisfield))[0] << (0 * 8);
                    lava_346 |= ((unsigned char *)(thisfield))[1] << (1 * 8);
                    lava_346 |= ((unsigned char *)(thisfield))[2] << (2 * 8);
                    lava_346 |= ((unsigned char *)(thisfield))[3] << (3 * 8);
                    lava_set(346, lava_346);
                    int lava_321 = 0;
                    lava_321 |= ((unsigned char *)(thisfield))[0] << (0 * 8);
                    lava_321 |= ((unsigned char *)(thisfield))[1] << (1 * 8);
                    lava_321 |= ((unsigned char *)(thisfield))[2] << (2 * 8);
                    lava_321 |= ((unsigned char *)(thisfield))[3] << (3 * 8);
                    lava_set(321, lava_321);
                    int lava_471 = 0;
                    lava_471 |= ((unsigned char *)(thisfield))[0] << (0 * 8);
                    lava_471 |= ((unsigned char *)(thisfield))[1] << (1 * 8);
                    lava_471 |= ((unsigned char *)(thisfield))[2] << (2 * 8);
                    lava_471 |= ((unsigned char *)(thisfield))[3] << (3 * 8);
                    lava_set(471, lava_471);
                    int lava_371 = 0;
                    lava_371 |= ((unsigned char *)(thisfield))[0] << (0 * 8);
                    lava_371 |= ((unsigned char *)(thisfield))[1] << (1 * 8);
                    lava_371 |= ((unsigned char *)(thisfield))[2] << (2 * 8);
                    lava_371 |= ((unsigned char *)(thisfield))[3] << (3 * 8);
                    lava_set(371, lava_371);
                    int lava_396 = 0;
                    lava_396 |= ((unsigned char *)(thisfield))[0] << (0 * 8);
                    lava_396 |= ((unsigned char *)(thisfield))[1] << (1 * 8);
                    lava_396 |= ((unsigned char *)(thisfield))[2] << (2 * 8);
                    lava_396 |= ((unsigned char *)(thisfield))[3] << (3 * 8);
                    lava_set(396, lava_396);
                }
                _Bool kbcieiubweuhc1365180540 = different(thisfield, prevfield, thislen, prevlen);
                
// ABS Label 277
if(((thisfield)) < 0)  {
	report_label_coverage("ABS", 277);
}

// COR Label 278
if((((thisfield)) || ((thisfield))) != (((thisfield)) && ((thisfield))))  {
	report_label_coverage("COR", 278);
}

// MCC Label 279
if(((thisfield)) && ((thisfield)) ) {
	report_label_coverage("MCC", 279);
}
// MCC Label 280
if(((thisfield)) && !(((thisfield))) ) {
	report_label_coverage("MCC", 280);
}
// MCC Label 281
if(!(((thisfield))) && ((thisfield)) ) {
	report_label_coverage("MCC", 281);
}
// MCC Label 282
if(!(((thisfield))) && !(((thisfield))) ) {
	report_label_coverage("MCC", 282);
}
if (((thisfield)) && ((thisfield))) {
                    int lava_447 = 0;
                    lava_447 |= ((unsigned char *)(thisfield))[0] << (0 * 8);
                    lava_447 |= ((unsigned char *)(thisfield))[1] << (1 * 8);
                    lava_447 |= ((unsigned char *)(thisfield))[2] << (2 * 8);
                    lava_447 |= ((unsigned char *)(thisfield))[3] << (3 * 8);
                    lava_set(447, lava_447);
                    int lava_297 = 0;
                    lava_297 |= ((unsigned char *)(thisfield))[0] << (0 * 8);
                    lava_297 |= ((unsigned char *)(thisfield))[1] << (1 * 8);
                    lava_297 |= ((unsigned char *)(thisfield))[2] << (2 * 8);
                    lava_297 |= ((unsigned char *)(thisfield))[3] << (3 * 8);
                    lava_set(297, lava_297);
                    int lava_347 = 0;
                    lava_347 |= ((unsigned char *)(thisfield))[0] << (0 * 8);
                    lava_347 |= ((unsigned char *)(thisfield))[1] << (1 * 8);
                    lava_347 |= ((unsigned char *)(thisfield))[2] << (2 * 8);
                    lava_347 |= ((unsigned char *)(thisfield))[3] << (3 * 8);
                    lava_set(347, lava_347);
                    int lava_322 = 0;
                    lava_322 |= ((unsigned char *)(thisfield))[0] << (0 * 8);
                    lava_322 |= ((unsigned char *)(thisfield))[1] << (1 * 8);
                    lava_322 |= ((unsigned char *)(thisfield))[2] << (2 * 8);
                    lava_322 |= ((unsigned char *)(thisfield))[3] << (3 * 8);
                    lava_set(322, lava_322);
                    int lava_472 = 0;
                    lava_472 |= ((unsigned char *)(thisfield))[0] << (0 * 8);
                    lava_472 |= ((unsigned char *)(thisfield))[1] << (1 * 8);
                    lava_472 |= ((unsigned char *)(thisfield))[2] << (2 * 8);
                    lava_472 |= ((unsigned char *)(thisfield))[3] << (3 * 8);
                    lava_set(472, lava_472);
                    int lava_372 = 0;
                    lava_372 |= ((unsigned char *)(thisfield))[0] << (0 * 8);
                    lava_372 |= ((unsigned char *)(thisfield))[1] << (1 * 8);
                    lava_372 |= ((unsigned char *)(thisfield))[2] << (2 * 8);
                    lava_372 |= ((unsigned char *)(thisfield))[3] << (3 * 8);
                    lava_set(372, lava_372);
                    int lava_397 = 0;
                    lava_397 |= ((unsigned char *)(thisfield))[0] << (0 * 8);
                    lava_397 |= ((unsigned char *)(thisfield))[1] << (1 * 8);
                    lava_397 |= ((unsigned char *)(thisfield))[2] << (2 * 8);
                    lava_397 |= ((unsigned char *)(thisfield))[3] << (3 * 8);
                    lava_set(397, lava_397);
                }
                kbcieiubweuhc1365180540;
            }));
            
// COR Label 283
if((new_group && grouping != GM_NONE || (grouping == GM_PREPEND || grouping == GM_BOTH || (first_group_printed && (grouping == GM_APPEND || grouping == GM_SEPARATE)))) != (new_group && grouping != GM_NONE && (grouping == GM_PREPEND || grouping == GM_BOTH || (first_group_printed && (grouping == GM_APPEND || grouping == GM_SEPARATE)))))  {
	report_label_coverage("COR", 283);
}
// COR Label 284
if((new_group || grouping != GM_NONE) != (new_group && grouping != GM_NONE))  {
	report_label_coverage("COR", 284);
}

// ROR Label 285
if((grouping == GM_NONE) != (grouping != GM_NONE))  {
	report_label_coverage("ROR", 285);
}

// MCC Label 286
if(new_group && grouping != GM_NONE && ( grouping == GM_PREPEND && grouping == GM_BOTH && ( first_group_printed && ( grouping == GM_APPEND && grouping == GM_SEPARATE ) ) ) ) {
	report_label_coverage("MCC", 286);
}
// MCC Label 287
if(new_group && grouping != GM_NONE && ( grouping == GM_PREPEND && grouping == GM_BOTH && ( first_group_printed && ( grouping == GM_APPEND && !(grouping == GM_SEPARATE) ) ) ) ) {
	report_label_coverage("MCC", 287);
}
// MCC Label 288
if(new_group && grouping != GM_NONE && ( grouping == GM_PREPEND && grouping == GM_BOTH && ( first_group_printed && ( !(grouping == GM_APPEND) && grouping == GM_SEPARATE ) ) ) ) {
	report_label_coverage("MCC", 288);
}
// MCC Label 289
if(new_group && grouping != GM_NONE && ( grouping == GM_PREPEND && grouping == GM_BOTH && ( first_group_printed && ( !(grouping == GM_APPEND) && !(grouping == GM_SEPARATE) ) ) ) ) {
	report_label_coverage("MCC", 289);
}
// MCC Label 290
if(new_group && grouping != GM_NONE && ( grouping == GM_PREPEND && grouping == GM_BOTH && ( !(first_group_printed) && ( grouping == GM_APPEND && grouping == GM_SEPARATE ) ) ) ) {
	report_label_coverage("MCC", 290);
}
// MCC Label 291
if(new_group && grouping != GM_NONE && ( grouping == GM_PREPEND && grouping == GM_BOTH && ( !(first_group_printed) && ( grouping == GM_APPEND && !(grouping == GM_SEPARATE) ) ) ) ) {
	report_label_coverage("MCC", 291);
}
// MCC Label 292
if(new_group && grouping != GM_NONE && ( grouping == GM_PREPEND && grouping == GM_BOTH && ( !(first_group_printed) && ( !(grouping == GM_APPEND) && grouping == GM_SEPARATE ) ) ) ) {
	report_label_coverage("MCC", 292);
}
// MCC Label 293
if(new_group && grouping != GM_NONE && ( grouping == GM_PREPEND && grouping == GM_BOTH && ( !(first_group_printed) && ( !(grouping == GM_APPEND) && !(grouping == GM_SEPARATE) ) ) ) ) {
	report_label_coverage("MCC", 293);
}
// MCC Label 294
if(new_group && grouping != GM_NONE && ( grouping == GM_PREPEND && !(grouping == GM_BOTH) && ( first_group_printed && ( grouping == GM_APPEND && grouping == GM_SEPARATE ) ) ) ) {
	report_label_coverage("MCC", 294);
}
// MCC Label 295
if(new_group && grouping != GM_NONE && ( grouping == GM_PREPEND && !(grouping == GM_BOTH) && ( first_group_printed && ( grouping == GM_APPEND && !(grouping == GM_SEPARATE) ) ) ) ) {
	report_label_coverage("MCC", 295);
}
// MCC Label 296
if(new_group && grouping != GM_NONE && ( grouping == GM_PREPEND && !(grouping == GM_BOTH) && ( first_group_printed && ( !(grouping == GM_APPEND) && grouping == GM_SEPARATE ) ) ) ) {
	report_label_coverage("MCC", 296);
}
// MCC Label 297
if(new_group && grouping != GM_NONE && ( grouping == GM_PREPEND && !(grouping == GM_BOTH) && ( first_group_printed && ( !(grouping == GM_APPEND) && !(grouping == GM_SEPARATE) ) ) ) ) {
	report_label_coverage("MCC", 297);
}
// MCC Label 298
if(new_group && grouping != GM_NONE && ( grouping == GM_PREPEND && !(grouping == GM_BOTH) && ( !(first_group_printed) && ( grouping == GM_APPEND && grouping == GM_SEPARATE ) ) ) ) {
	report_label_coverage("MCC", 298);
}
// MCC Label 299
if(new_group && grouping != GM_NONE && ( grouping == GM_PREPEND && !(grouping == GM_BOTH) && ( !(first_group_printed) && ( grouping == GM_APPEND && !(grouping == GM_SEPARATE) ) ) ) ) {
	report_label_coverage("MCC", 299);
}
// MCC Label 300
if(new_group && grouping != GM_NONE && ( grouping == GM_PREPEND && !(grouping == GM_BOTH) && ( !(first_group_printed) && ( !(grouping == GM_APPEND) && grouping == GM_SEPARATE ) ) ) ) {
	report_label_coverage("MCC", 300);
}
// MCC Label 301
if(new_group && grouping != GM_NONE && ( grouping == GM_PREPEND && !(grouping == GM_BOTH) && ( !(first_group_printed) && ( !(grouping == GM_APPEND) && !(grouping == GM_SEPARATE) ) ) ) ) {
	report_label_coverage("MCC", 301);
}
// MCC Label 302
if(new_group && grouping != GM_NONE && ( !(grouping == GM_PREPEND) && grouping == GM_BOTH && ( first_group_printed && ( grouping == GM_APPEND && grouping == GM_SEPARATE ) ) ) ) {
	report_label_coverage("MCC", 302);
}
// MCC Label 303
if(new_group && grouping != GM_NONE && ( !(grouping == GM_PREPEND) && grouping == GM_BOTH && ( first_group_printed && ( grouping == GM_APPEND && !(grouping == GM_SEPARATE) ) ) ) ) {
	report_label_coverage("MCC", 303);
}
// MCC Label 304
if(new_group && grouping != GM_NONE && ( !(grouping == GM_PREPEND) && grouping == GM_BOTH && ( first_group_printed && ( !(grouping == GM_APPEND) && grouping == GM_SEPARATE ) ) ) ) {
	report_label_coverage("MCC", 304);
}
// MCC Label 305
if(new_group && grouping != GM_NONE && ( !(grouping == GM_PREPEND) && grouping == GM_BOTH && ( first_group_printed && ( !(grouping == GM_APPEND) && !(grouping == GM_SEPARATE) ) ) ) ) {
	report_label_coverage("MCC", 305);
}
// MCC Label 306
if(new_group && grouping != GM_NONE && ( !(grouping == GM_PREPEND) && grouping == GM_BOTH && ( !(first_group_printed) && ( grouping == GM_APPEND && grouping == GM_SEPARATE ) ) ) ) {
	report_label_coverage("MCC", 306);
}
// MCC Label 307
if(new_group && grouping != GM_NONE && ( !(grouping == GM_PREPEND) && grouping == GM_BOTH && ( !(first_group_printed) && ( grouping == GM_APPEND && !(grouping == GM_SEPARATE) ) ) ) ) {
	report_label_coverage("MCC", 307);
}
// MCC Label 308
if(new_group && grouping != GM_NONE && ( !(grouping == GM_PREPEND) && grouping == GM_BOTH && ( !(first_group_printed) && ( !(grouping == GM_APPEND) && grouping == GM_SEPARATE ) ) ) ) {
	report_label_coverage("MCC", 308);
}
// MCC Label 309
if(new_group && grouping != GM_NONE && ( !(grouping == GM_PREPEND) && grouping == GM_BOTH && ( !(first_group_printed) && ( !(grouping == GM_APPEND) && !(grouping == GM_SEPARATE) ) ) ) ) {
	report_label_coverage("MCC", 309);
}
// MCC Label 310
if(new_group && grouping != GM_NONE && ( !(grouping == GM_PREPEND) && !(grouping == GM_BOTH) && ( first_group_printed && ( grouping == GM_APPEND && grouping == GM_SEPARATE ) ) ) ) {
	report_label_coverage("MCC", 310);
}
// MCC Label 311
if(new_group && grouping != GM_NONE && ( !(grouping == GM_PREPEND) && !(grouping == GM_BOTH) && ( first_group_printed && ( grouping == GM_APPEND && !(grouping == GM_SEPARATE) ) ) ) ) {
	report_label_coverage("MCC", 311);
}
// MCC Label 312
if(new_group && grouping != GM_NONE && ( !(grouping == GM_PREPEND) && !(grouping == GM_BOTH) && ( first_group_printed && ( !(grouping == GM_APPEND) && grouping == GM_SEPARATE ) ) ) ) {
	report_label_coverage("MCC", 312);
}
// MCC Label 313
if(new_group && grouping != GM_NONE && ( !(grouping == GM_PREPEND) && !(grouping == GM_BOTH) && ( first_group_printed && ( !(grouping == GM_APPEND) && !(grouping == GM_SEPARATE) ) ) ) ) {
	report_label_coverage("MCC", 313);
}
// MCC Label 314
if(new_group && grouping != GM_NONE && ( !(grouping == GM_PREPEND) && !(grouping == GM_BOTH) && ( !(first_group_printed) && ( grouping == GM_APPEND && grouping == GM_SEPARATE ) ) ) ) {
	report_label_coverage("MCC", 314);
}
// MCC Label 315
if(new_group && grouping != GM_NONE && ( !(grouping == GM_PREPEND) && !(grouping == GM_BOTH) && ( !(first_group_printed) && ( grouping == GM_APPEND && !(grouping == GM_SEPARATE) ) ) ) ) {
	report_label_coverage("MCC", 315);
}
// MCC Label 316
if(new_group && grouping != GM_NONE && ( !(grouping == GM_PREPEND) && !(grouping == GM_BOTH) && ( !(first_group_printed) && ( !(grouping == GM_APPEND) && grouping == GM_SEPARATE ) ) ) ) {
	report_label_coverage("MCC", 316);
}
// MCC Label 317
if(new_group && grouping != GM_NONE && ( !(grouping == GM_PREPEND) && !(grouping == GM_BOTH) && ( !(first_group_printed) && ( !(grouping == GM_APPEND) && !(grouping == GM_SEPARATE) ) ) ) ) {
	report_label_coverage("MCC", 317);
}
// MCC Label 318
if(new_group && !(grouping != GM_NONE) && ( grouping == GM_PREPEND && grouping == GM_BOTH && ( first_group_printed && ( grouping == GM_APPEND && grouping == GM_SEPARATE ) ) ) ) {
	report_label_coverage("MCC", 318);
}
// MCC Label 319
if(new_group && !(grouping != GM_NONE) && ( grouping == GM_PREPEND && grouping == GM_BOTH && ( first_group_printed && ( grouping == GM_APPEND && !(grouping == GM_SEPARATE) ) ) ) ) {
	report_label_coverage("MCC", 319);
}
// MCC Label 320
if(new_group && !(grouping != GM_NONE) && ( grouping == GM_PREPEND && grouping == GM_BOTH && ( first_group_printed && ( !(grouping == GM_APPEND) && grouping == GM_SEPARATE ) ) ) ) {
	report_label_coverage("MCC", 320);
}
// MCC Label 321
if(new_group && !(grouping != GM_NONE) && ( grouping == GM_PREPEND && grouping == GM_BOTH && ( first_group_printed && ( !(grouping == GM_APPEND) && !(grouping == GM_SEPARATE) ) ) ) ) {
	report_label_coverage("MCC", 321);
}
// MCC Label 322
if(new_group && !(grouping != GM_NONE) && ( grouping == GM_PREPEND && grouping == GM_BOTH && ( !(first_group_printed) && ( grouping == GM_APPEND && grouping == GM_SEPARATE ) ) ) ) {
	report_label_coverage("MCC", 322);
}
// MCC Label 323
if(new_group && !(grouping != GM_NONE) && ( grouping == GM_PREPEND && grouping == GM_BOTH && ( !(first_group_printed) && ( grouping == GM_APPEND && !(grouping == GM_SEPARATE) ) ) ) ) {
	report_label_coverage("MCC", 323);
}
// MCC Label 324
if(new_group && !(grouping != GM_NONE) && ( grouping == GM_PREPEND && grouping == GM_BOTH && ( !(first_group_printed) && ( !(grouping == GM_APPEND) && grouping == GM_SEPARATE ) ) ) ) {
	report_label_coverage("MCC", 324);
}
// MCC Label 325
if(new_group && !(grouping != GM_NONE) && ( grouping == GM_PREPEND && grouping == GM_BOTH && ( !(first_group_printed) && ( !(grouping == GM_APPEND) && !(grouping == GM_SEPARATE) ) ) ) ) {
	report_label_coverage("MCC", 325);
}
// MCC Label 326
if(new_group && !(grouping != GM_NONE) && ( grouping == GM_PREPEND && !(grouping == GM_BOTH) && ( first_group_printed && ( grouping == GM_APPEND && grouping == GM_SEPARATE ) ) ) ) {
	report_label_coverage("MCC", 326);
}
// MCC Label 327
if(new_group && !(grouping != GM_NONE) && ( grouping == GM_PREPEND && !(grouping == GM_BOTH) && ( first_group_printed && ( grouping == GM_APPEND && !(grouping == GM_SEPARATE) ) ) ) ) {
	report_label_coverage("MCC", 327);
}
// MCC Label 328
if(new_group && !(grouping != GM_NONE) && ( grouping == GM_PREPEND && !(grouping == GM_BOTH) && ( first_group_printed && ( !(grouping == GM_APPEND) && grouping == GM_SEPARATE ) ) ) ) {
	report_label_coverage("MCC", 328);
}
// MCC Label 329
if(new_group && !(grouping != GM_NONE) && ( grouping == GM_PREPEND && !(grouping == GM_BOTH) && ( first_group_printed && ( !(grouping == GM_APPEND) && !(grouping == GM_SEPARATE) ) ) ) ) {
	report_label_coverage("MCC", 329);
}
// MCC Label 330
if(new_group && !(grouping != GM_NONE) && ( grouping == GM_PREPEND && !(grouping == GM_BOTH) && ( !(first_group_printed) && ( grouping == GM_APPEND && grouping == GM_SEPARATE ) ) ) ) {
	report_label_coverage("MCC", 330);
}
// MCC Label 331
if(new_group && !(grouping != GM_NONE) && ( grouping == GM_PREPEND && !(grouping == GM_BOTH) && ( !(first_group_printed) && ( grouping == GM_APPEND && !(grouping == GM_SEPARATE) ) ) ) ) {
	report_label_coverage("MCC", 331);
}
// MCC Label 332
if(new_group && !(grouping != GM_NONE) && ( grouping == GM_PREPEND && !(grouping == GM_BOTH) && ( !(first_group_printed) && ( !(grouping == GM_APPEND) && grouping == GM_SEPARATE ) ) ) ) {
	report_label_coverage("MCC", 332);
}
// MCC Label 333
if(new_group && !(grouping != GM_NONE) && ( grouping == GM_PREPEND && !(grouping == GM_BOTH) && ( !(first_group_printed) && ( !(grouping == GM_APPEND) && !(grouping == GM_SEPARATE) ) ) ) ) {
	report_label_coverage("MCC", 333);
}
// MCC Label 334
if(new_group && !(grouping != GM_NONE) && ( !(grouping == GM_PREPEND) && grouping == GM_BOTH && ( first_group_printed && ( grouping == GM_APPEND && grouping == GM_SEPARATE ) ) ) ) {
	report_label_coverage("MCC", 334);
}
// MCC Label 335
if(new_group && !(grouping != GM_NONE) && ( !(grouping == GM_PREPEND) && grouping == GM_BOTH && ( first_group_printed && ( grouping == GM_APPEND && !(grouping == GM_SEPARATE) ) ) ) ) {
	report_label_coverage("MCC", 335);
}
// MCC Label 336
if(new_group && !(grouping != GM_NONE) && ( !(grouping == GM_PREPEND) && grouping == GM_BOTH && ( first_group_printed && ( !(grouping == GM_APPEND) && grouping == GM_SEPARATE ) ) ) ) {
	report_label_coverage("MCC", 336);
}
// MCC Label 337
if(new_group && !(grouping != GM_NONE) && ( !(grouping == GM_PREPEND) && grouping == GM_BOTH && ( first_group_printed && ( !(grouping == GM_APPEND) && !(grouping == GM_SEPARATE) ) ) ) ) {
	report_label_coverage("MCC", 337);
}
// MCC Label 338
if(new_group && !(grouping != GM_NONE) && ( !(grouping == GM_PREPEND) && grouping == GM_BOTH && ( !(first_group_printed) && ( grouping == GM_APPEND && grouping == GM_SEPARATE ) ) ) ) {
	report_label_coverage("MCC", 338);
}
// MCC Label 339
if(new_group && !(grouping != GM_NONE) && ( !(grouping == GM_PREPEND) && grouping == GM_BOTH && ( !(first_group_printed) && ( grouping == GM_APPEND && !(grouping == GM_SEPARATE) ) ) ) ) {
	report_label_coverage("MCC", 339);
}
// MCC Label 340
if(new_group && !(grouping != GM_NONE) && ( !(grouping == GM_PREPEND) && grouping == GM_BOTH && ( !(first_group_printed) && ( !(grouping == GM_APPEND) && grouping == GM_SEPARATE ) ) ) ) {
	report_label_coverage("MCC", 340);
}
// MCC Label 341
if(new_group && !(grouping != GM_NONE) && ( !(grouping == GM_PREPEND) && grouping == GM_BOTH && ( !(first_group_printed) && ( !(grouping == GM_APPEND) && !(grouping == GM_SEPARATE) ) ) ) ) {
	report_label_coverage("MCC", 341);
}
// MCC Label 342
if(new_group && !(grouping != GM_NONE) && ( !(grouping == GM_PREPEND) && !(grouping == GM_BOTH) && ( first_group_printed && ( grouping == GM_APPEND && grouping == GM_SEPARATE ) ) ) ) {
	report_label_coverage("MCC", 342);
}
// MCC Label 343
if(new_group && !(grouping != GM_NONE) && ( !(grouping == GM_PREPEND) && !(grouping == GM_BOTH) && ( first_group_printed && ( grouping == GM_APPEND && !(grouping == GM_SEPARATE) ) ) ) ) {
	report_label_coverage("MCC", 343);
}
// MCC Label 344
if(new_group && !(grouping != GM_NONE) && ( !(grouping == GM_PREPEND) && !(grouping == GM_BOTH) && ( first_group_printed && ( !(grouping == GM_APPEND) && grouping == GM_SEPARATE ) ) ) ) {
	report_label_coverage("MCC", 344);
}
// MCC Label 345
if(new_group && !(grouping != GM_NONE) && ( !(grouping == GM_PREPEND) && !(grouping == GM_BOTH) && ( first_group_printed && ( !(grouping == GM_APPEND) && !(grouping == GM_SEPARATE) ) ) ) ) {
	report_label_coverage("MCC", 345);
}
// MCC Label 346
if(new_group && !(grouping != GM_NONE) && ( !(grouping == GM_PREPEND) && !(grouping == GM_BOTH) && ( !(first_group_printed) && ( grouping == GM_APPEND && grouping == GM_SEPARATE ) ) ) ) {
	report_label_coverage("MCC", 346);
}
// MCC Label 347
if(new_group && !(grouping != GM_NONE) && ( !(grouping == GM_PREPEND) && !(grouping == GM_BOTH) && ( !(first_group_printed) && ( grouping == GM_APPEND && !(grouping == GM_SEPARATE) ) ) ) ) {
	report_label_coverage("MCC", 347);
}
// MCC Label 348
if(new_group && !(grouping != GM_NONE) && ( !(grouping == GM_PREPEND) && !(grouping == GM_BOTH) && ( !(first_group_printed) && ( !(grouping == GM_APPEND) && grouping == GM_SEPARATE ) ) ) ) {
	report_label_coverage("MCC", 348);
}
// MCC Label 349
if(new_group && !(grouping != GM_NONE) && ( !(grouping == GM_PREPEND) && !(grouping == GM_BOTH) && ( !(first_group_printed) && ( !(grouping == GM_APPEND) && !(grouping == GM_SEPARATE) ) ) ) ) {
	report_label_coverage("MCC", 349);
}
// MCC Label 350
if(!(new_group) && grouping != GM_NONE && ( grouping == GM_PREPEND && grouping == GM_BOTH && ( first_group_printed && ( grouping == GM_APPEND && grouping == GM_SEPARATE ) ) ) ) {
	report_label_coverage("MCC", 350);
}
// MCC Label 351
if(!(new_group) && grouping != GM_NONE && ( grouping == GM_PREPEND && grouping == GM_BOTH && ( first_group_printed && ( grouping == GM_APPEND && !(grouping == GM_SEPARATE) ) ) ) ) {
	report_label_coverage("MCC", 351);
}
// MCC Label 352
if(!(new_group) && grouping != GM_NONE && ( grouping == GM_PREPEND && grouping == GM_BOTH && ( first_group_printed && ( !(grouping == GM_APPEND) && grouping == GM_SEPARATE ) ) ) ) {
	report_label_coverage("MCC", 352);
}
// MCC Label 353
if(!(new_group) && grouping != GM_NONE && ( grouping == GM_PREPEND && grouping == GM_BOTH && ( first_group_printed && ( !(grouping == GM_APPEND) && !(grouping == GM_SEPARATE) ) ) ) ) {
	report_label_coverage("MCC", 353);
}
// MCC Label 354
if(!(new_group) && grouping != GM_NONE && ( grouping == GM_PREPEND && grouping == GM_BOTH && ( !(first_group_printed) && ( grouping == GM_APPEND && grouping == GM_SEPARATE ) ) ) ) {
	report_label_coverage("MCC", 354);
}
// MCC Label 355
if(!(new_group) && grouping != GM_NONE && ( grouping == GM_PREPEND && grouping == GM_BOTH && ( !(first_group_printed) && ( grouping == GM_APPEND && !(grouping == GM_SEPARATE) ) ) ) ) {
	report_label_coverage("MCC", 355);
}
// MCC Label 356
if(!(new_group) && grouping != GM_NONE && ( grouping == GM_PREPEND && grouping == GM_BOTH && ( !(first_group_printed) && ( !(grouping == GM_APPEND) && grouping == GM_SEPARATE ) ) ) ) {
	report_label_coverage("MCC", 356);
}
// MCC Label 357
if(!(new_group) && grouping != GM_NONE && ( grouping == GM_PREPEND && grouping == GM_BOTH && ( !(first_group_printed) && ( !(grouping == GM_APPEND) && !(grouping == GM_SEPARATE) ) ) ) ) {
	report_label_coverage("MCC", 357);
}
// MCC Label 358
if(!(new_group) && grouping != GM_NONE && ( grouping == GM_PREPEND && !(grouping == GM_BOTH) && ( first_group_printed && ( grouping == GM_APPEND && grouping == GM_SEPARATE ) ) ) ) {
	report_label_coverage("MCC", 358);
}
// MCC Label 359
if(!(new_group) && grouping != GM_NONE && ( grouping == GM_PREPEND && !(grouping == GM_BOTH) && ( first_group_printed && ( grouping == GM_APPEND && !(grouping == GM_SEPARATE) ) ) ) ) {
	report_label_coverage("MCC", 359);
}
// MCC Label 360
if(!(new_group) && grouping != GM_NONE && ( grouping == GM_PREPEND && !(grouping == GM_BOTH) && ( first_group_printed && ( !(grouping == GM_APPEND) && grouping == GM_SEPARATE ) ) ) ) {
	report_label_coverage("MCC", 360);
}
// MCC Label 361
if(!(new_group) && grouping != GM_NONE && ( grouping == GM_PREPEND && !(grouping == GM_BOTH) && ( first_group_printed && ( !(grouping == GM_APPEND) && !(grouping == GM_SEPARATE) ) ) ) ) {
	report_label_coverage("MCC", 361);
}
// MCC Label 362
if(!(new_group) && grouping != GM_NONE && ( grouping == GM_PREPEND && !(grouping == GM_BOTH) && ( !(first_group_printed) && ( grouping == GM_APPEND && grouping == GM_SEPARATE ) ) ) ) {
	report_label_coverage("MCC", 362);
}
// MCC Label 363
if(!(new_group) && grouping != GM_NONE && ( grouping == GM_PREPEND && !(grouping == GM_BOTH) && ( !(first_group_printed) && ( grouping == GM_APPEND && !(grouping == GM_SEPARATE) ) ) ) ) {
	report_label_coverage("MCC", 363);
}
// MCC Label 364
if(!(new_group) && grouping != GM_NONE && ( grouping == GM_PREPEND && !(grouping == GM_BOTH) && ( !(first_group_printed) && ( !(grouping == GM_APPEND) && grouping == GM_SEPARATE ) ) ) ) {
	report_label_coverage("MCC", 364);
}
// MCC Label 365
if(!(new_group) && grouping != GM_NONE && ( grouping == GM_PREPEND && !(grouping == GM_BOTH) && ( !(first_group_printed) && ( !(grouping == GM_APPEND) && !(grouping == GM_SEPARATE) ) ) ) ) {
	report_label_coverage("MCC", 365);
}
// MCC Label 366
if(!(new_group) && grouping != GM_NONE && ( !(grouping == GM_PREPEND) && grouping == GM_BOTH && ( first_group_printed && ( grouping == GM_APPEND && grouping == GM_SEPARATE ) ) ) ) {
	report_label_coverage("MCC", 366);
}
// MCC Label 367
if(!(new_group) && grouping != GM_NONE && ( !(grouping == GM_PREPEND) && grouping == GM_BOTH && ( first_group_printed && ( grouping == GM_APPEND && !(grouping == GM_SEPARATE) ) ) ) ) {
	report_label_coverage("MCC", 367);
}
// MCC Label 368
if(!(new_group) && grouping != GM_NONE && ( !(grouping == GM_PREPEND) && grouping == GM_BOTH && ( first_group_printed && ( !(grouping == GM_APPEND) && grouping == GM_SEPARATE ) ) ) ) {
	report_label_coverage("MCC", 368);
}
// MCC Label 369
if(!(new_group) && grouping != GM_NONE && ( !(grouping == GM_PREPEND) && grouping == GM_BOTH && ( first_group_printed && ( !(grouping == GM_APPEND) && !(grouping == GM_SEPARATE) ) ) ) ) {
	report_label_coverage("MCC", 369);
}
// MCC Label 370
if(!(new_group) && grouping != GM_NONE && ( !(grouping == GM_PREPEND) && grouping == GM_BOTH && ( !(first_group_printed) && ( grouping == GM_APPEND && grouping == GM_SEPARATE ) ) ) ) {
	report_label_coverage("MCC", 370);
}
// MCC Label 371
if(!(new_group) && grouping != GM_NONE && ( !(grouping == GM_PREPEND) && grouping == GM_BOTH && ( !(first_group_printed) && ( grouping == GM_APPEND && !(grouping == GM_SEPARATE) ) ) ) ) {
	report_label_coverage("MCC", 371);
}
// MCC Label 372
if(!(new_group) && grouping != GM_NONE && ( !(grouping == GM_PREPEND) && grouping == GM_BOTH && ( !(first_group_printed) && ( !(grouping == GM_APPEND) && grouping == GM_SEPARATE ) ) ) ) {
	report_label_coverage("MCC", 372);
}
// MCC Label 373
if(!(new_group) && grouping != GM_NONE && ( !(grouping == GM_PREPEND) && grouping == GM_BOTH && ( !(first_group_printed) && ( !(grouping == GM_APPEND) && !(grouping == GM_SEPARATE) ) ) ) ) {
	report_label_coverage("MCC", 373);
}
// MCC Label 374
if(!(new_group) && grouping != GM_NONE && ( !(grouping == GM_PREPEND) && !(grouping == GM_BOTH) && ( first_group_printed && ( grouping == GM_APPEND && grouping == GM_SEPARATE ) ) ) ) {
	report_label_coverage("MCC", 374);
}
// MCC Label 375
if(!(new_group) && grouping != GM_NONE && ( !(grouping == GM_PREPEND) && !(grouping == GM_BOTH) && ( first_group_printed && ( grouping == GM_APPEND && !(grouping == GM_SEPARATE) ) ) ) ) {
	report_label_coverage("MCC", 375);
}
// MCC Label 376
if(!(new_group) && grouping != GM_NONE && ( !(grouping == GM_PREPEND) && !(grouping == GM_BOTH) && ( first_group_printed && ( !(grouping == GM_APPEND) && grouping == GM_SEPARATE ) ) ) ) {
	report_label_coverage("MCC", 376);
}
// MCC Label 377
if(!(new_group) && grouping != GM_NONE && ( !(grouping == GM_PREPEND) && !(grouping == GM_BOTH) && ( first_group_printed && ( !(grouping == GM_APPEND) && !(grouping == GM_SEPARATE) ) ) ) ) {
	report_label_coverage("MCC", 377);
}
// MCC Label 378
if(!(new_group) && grouping != GM_NONE && ( !(grouping == GM_PREPEND) && !(grouping == GM_BOTH) && ( !(first_group_printed) && ( grouping == GM_APPEND && grouping == GM_SEPARATE ) ) ) ) {
	report_label_coverage("MCC", 378);
}
// MCC Label 379
if(!(new_group) && grouping != GM_NONE && ( !(grouping == GM_PREPEND) && !(grouping == GM_BOTH) && ( !(first_group_printed) && ( grouping == GM_APPEND && !(grouping == GM_SEPARATE) ) ) ) ) {
	report_label_coverage("MCC", 379);
}
// MCC Label 380
if(!(new_group) && grouping != GM_NONE && ( !(grouping == GM_PREPEND) && !(grouping == GM_BOTH) && ( !(first_group_printed) && ( !(grouping == GM_APPEND) && grouping == GM_SEPARATE ) ) ) ) {
	report_label_coverage("MCC", 380);
}
// MCC Label 381
if(!(new_group) && grouping != GM_NONE && ( !(grouping == GM_PREPEND) && !(grouping == GM_BOTH) && ( !(first_group_printed) && ( !(grouping == GM_APPEND) && !(grouping == GM_SEPARATE) ) ) ) ) {
	report_label_coverage("MCC", 381);
}
// MCC Label 382
if(!(new_group) && !(grouping != GM_NONE) && ( grouping == GM_PREPEND && grouping == GM_BOTH && ( first_group_printed && ( grouping == GM_APPEND && grouping == GM_SEPARATE ) ) ) ) {
	report_label_coverage("MCC", 382);
}
// MCC Label 383
if(!(new_group) && !(grouping != GM_NONE) && ( grouping == GM_PREPEND && grouping == GM_BOTH && ( first_group_printed && ( grouping == GM_APPEND && !(grouping == GM_SEPARATE) ) ) ) ) {
	report_label_coverage("MCC", 383);
}
// MCC Label 384
if(!(new_group) && !(grouping != GM_NONE) && ( grouping == GM_PREPEND && grouping == GM_BOTH && ( first_group_printed && ( !(grouping == GM_APPEND) && grouping == GM_SEPARATE ) ) ) ) {
	report_label_coverage("MCC", 384);
}
// MCC Label 385
if(!(new_group) && !(grouping != GM_NONE) && ( grouping == GM_PREPEND && grouping == GM_BOTH && ( first_group_printed && ( !(grouping == GM_APPEND) && !(grouping == GM_SEPARATE) ) ) ) ) {
	report_label_coverage("MCC", 385);
}
// MCC Label 386
if(!(new_group) && !(grouping != GM_NONE) && ( grouping == GM_PREPEND && grouping == GM_BOTH && ( !(first_group_printed) && ( grouping == GM_APPEND && grouping == GM_SEPARATE ) ) ) ) {
	report_label_coverage("MCC", 386);
}
// MCC Label 387
if(!(new_group) && !(grouping != GM_NONE) && ( grouping == GM_PREPEND && grouping == GM_BOTH && ( !(first_group_printed) && ( grouping == GM_APPEND && !(grouping == GM_SEPARATE) ) ) ) ) {
	report_label_coverage("MCC", 387);
}
// MCC Label 388
if(!(new_group) && !(grouping != GM_NONE) && ( grouping == GM_PREPEND && grouping == GM_BOTH && ( !(first_group_printed) && ( !(grouping == GM_APPEND) && grouping == GM_SEPARATE ) ) ) ) {
	report_label_coverage("MCC", 388);
}
// MCC Label 389
if(!(new_group) && !(grouping != GM_NONE) && ( grouping == GM_PREPEND && grouping == GM_BOTH && ( !(first_group_printed) && ( !(grouping == GM_APPEND) && !(grouping == GM_SEPARATE) ) ) ) ) {
	report_label_coverage("MCC", 389);
}
// MCC Label 390
if(!(new_group) && !(grouping != GM_NONE) && ( grouping == GM_PREPEND && !(grouping == GM_BOTH) && ( first_group_printed && ( grouping == GM_APPEND && grouping == GM_SEPARATE ) ) ) ) {
	report_label_coverage("MCC", 390);
}
// MCC Label 391
if(!(new_group) && !(grouping != GM_NONE) && ( grouping == GM_PREPEND && !(grouping == GM_BOTH) && ( first_group_printed && ( grouping == GM_APPEND && !(grouping == GM_SEPARATE) ) ) ) ) {
	report_label_coverage("MCC", 391);
}
// MCC Label 392
if(!(new_group) && !(grouping != GM_NONE) && ( grouping == GM_PREPEND && !(grouping == GM_BOTH) && ( first_group_printed && ( !(grouping == GM_APPEND) && grouping == GM_SEPARATE ) ) ) ) {
	report_label_coverage("MCC", 392);
}
// MCC Label 393
if(!(new_group) && !(grouping != GM_NONE) && ( grouping == GM_PREPEND && !(grouping == GM_BOTH) && ( first_group_printed && ( !(grouping == GM_APPEND) && !(grouping == GM_SEPARATE) ) ) ) ) {
	report_label_coverage("MCC", 393);
}
// MCC Label 394
if(!(new_group) && !(grouping != GM_NONE) && ( grouping == GM_PREPEND && !(grouping == GM_BOTH) && ( !(first_group_printed) && ( grouping == GM_APPEND && grouping == GM_SEPARATE ) ) ) ) {
	report_label_coverage("MCC", 394);
}
// MCC Label 395
if(!(new_group) && !(grouping != GM_NONE) && ( grouping == GM_PREPEND && !(grouping == GM_BOTH) && ( !(first_group_printed) && ( grouping == GM_APPEND && !(grouping == GM_SEPARATE) ) ) ) ) {
	report_label_coverage("MCC", 395);
}
// MCC Label 396
if(!(new_group) && !(grouping != GM_NONE) && ( grouping == GM_PREPEND && !(grouping == GM_BOTH) && ( !(first_group_printed) && ( !(grouping == GM_APPEND) && grouping == GM_SEPARATE ) ) ) ) {
	report_label_coverage("MCC", 396);
}
// MCC Label 397
if(!(new_group) && !(grouping != GM_NONE) && ( grouping == GM_PREPEND && !(grouping == GM_BOTH) && ( !(first_group_printed) && ( !(grouping == GM_APPEND) && !(grouping == GM_SEPARATE) ) ) ) ) {
	report_label_coverage("MCC", 397);
}
// MCC Label 398
if(!(new_group) && !(grouping != GM_NONE) && ( !(grouping == GM_PREPEND) && grouping == GM_BOTH && ( first_group_printed && ( grouping == GM_APPEND && grouping == GM_SEPARATE ) ) ) ) {
	report_label_coverage("MCC", 398);
}
// MCC Label 399
if(!(new_group) && !(grouping != GM_NONE) && ( !(grouping == GM_PREPEND) && grouping == GM_BOTH && ( first_group_printed && ( grouping == GM_APPEND && !(grouping == GM_SEPARATE) ) ) ) ) {
	report_label_coverage("MCC", 399);
}
// MCC Label 400
if(!(new_group) && !(grouping != GM_NONE) && ( !(grouping == GM_PREPEND) && grouping == GM_BOTH && ( first_group_printed && ( !(grouping == GM_APPEND) && grouping == GM_SEPARATE ) ) ) ) {
	report_label_coverage("MCC", 400);
}
// MCC Label 401
if(!(new_group) && !(grouping != GM_NONE) && ( !(grouping == GM_PREPEND) && grouping == GM_BOTH && ( first_group_printed && ( !(grouping == GM_APPEND) && !(grouping == GM_SEPARATE) ) ) ) ) {
	report_label_coverage("MCC", 401);
}
// MCC Label 402
if(!(new_group) && !(grouping != GM_NONE) && ( !(grouping == GM_PREPEND) && grouping == GM_BOTH && ( !(first_group_printed) && ( grouping == GM_APPEND && grouping == GM_SEPARATE ) ) ) ) {
	report_label_coverage("MCC", 402);
}
// MCC Label 403
if(!(new_group) && !(grouping != GM_NONE) && ( !(grouping == GM_PREPEND) && grouping == GM_BOTH && ( !(first_group_printed) && ( grouping == GM_APPEND && !(grouping == GM_SEPARATE) ) ) ) ) {
	report_label_coverage("MCC", 403);
}
// MCC Label 404
if(!(new_group) && !(grouping != GM_NONE) && ( !(grouping == GM_PREPEND) && grouping == GM_BOTH && ( !(first_group_printed) && ( !(grouping == GM_APPEND) && grouping == GM_SEPARATE ) ) ) ) {
	report_label_coverage("MCC", 404);
}
// MCC Label 405
if(!(new_group) && !(grouping != GM_NONE) && ( !(grouping == GM_PREPEND) && grouping == GM_BOTH && ( !(first_group_printed) && ( !(grouping == GM_APPEND) && !(grouping == GM_SEPARATE) ) ) ) ) {
	report_label_coverage("MCC", 405);
}
// MCC Label 406
if(!(new_group) && !(grouping != GM_NONE) && ( !(grouping == GM_PREPEND) && !(grouping == GM_BOTH) && ( first_group_printed && ( grouping == GM_APPEND && grouping == GM_SEPARATE ) ) ) ) {
	report_label_coverage("MCC", 406);
}
// MCC Label 407
if(!(new_group) && !(grouping != GM_NONE) && ( !(grouping == GM_PREPEND) && !(grouping == GM_BOTH) && ( first_group_printed && ( grouping == GM_APPEND && !(grouping == GM_SEPARATE) ) ) ) ) {
	report_label_coverage("MCC", 407);
}
// MCC Label 408
if(!(new_group) && !(grouping != GM_NONE) && ( !(grouping == GM_PREPEND) && !(grouping == GM_BOTH) && ( first_group_printed && ( !(grouping == GM_APPEND) && grouping == GM_SEPARATE ) ) ) ) {
	report_label_coverage("MCC", 408);
}
// MCC Label 409
if(!(new_group) && !(grouping != GM_NONE) && ( !(grouping == GM_PREPEND) && !(grouping == GM_BOTH) && ( first_group_printed && ( !(grouping == GM_APPEND) && !(grouping == GM_SEPARATE) ) ) ) ) {
	report_label_coverage("MCC", 409);
}
// MCC Label 410
if(!(new_group) && !(grouping != GM_NONE) && ( !(grouping == GM_PREPEND) && !(grouping == GM_BOTH) && ( !(first_group_printed) && ( grouping == GM_APPEND && grouping == GM_SEPARATE ) ) ) ) {
	report_label_coverage("MCC", 410);
}
// MCC Label 411
if(!(new_group) && !(grouping != GM_NONE) && ( !(grouping == GM_PREPEND) && !(grouping == GM_BOTH) && ( !(first_group_printed) && ( grouping == GM_APPEND && !(grouping == GM_SEPARATE) ) ) ) ) {
	report_label_coverage("MCC", 411);
}
// MCC Label 412
if(!(new_group) && !(grouping != GM_NONE) && ( !(grouping == GM_PREPEND) && !(grouping == GM_BOTH) && ( !(first_group_printed) && ( !(grouping == GM_APPEND) && grouping == GM_SEPARATE ) ) ) ) {
	report_label_coverage("MCC", 412);
}
// MCC Label 413
if(!(new_group) && !(grouping != GM_NONE) && ( !(grouping == GM_PREPEND) && !(grouping == GM_BOTH) && ( !(first_group_printed) && ( !(grouping == GM_APPEND) && !(grouping == GM_SEPARATE) ) ) ) ) {
	report_label_coverage("MCC", 413);
}
if (new_group && grouping != GM_NONE && (grouping == GM_PREPEND || grouping == GM_BOTH || (first_group_printed && (grouping == GM_APPEND || grouping == GM_SEPARATE))))
                putchar_unlocked(delimiter);
            
// COR Label 414
if((new_group && grouping != GM_NONE) != (new_group || grouping != GM_NONE))  {
	report_label_coverage("COR", 414);
}

// ROR Label 415
if((grouping == GM_NONE) != (grouping != GM_NONE))  {
	report_label_coverage("ROR", 415);
}

// MCC Label 416
if(new_group && grouping != GM_NONE ) {
	report_label_coverage("MCC", 416);
}
// MCC Label 417
if(new_group && !(grouping != GM_NONE) ) {
	report_label_coverage("MCC", 417);
}
// MCC Label 418
if(!(new_group) && grouping != GM_NONE ) {
	report_label_coverage("MCC", 418);
}
// MCC Label 419
if(!(new_group) && !(grouping != GM_NONE) ) {
	report_label_coverage("MCC", 419);
}
if (new_group || grouping != GM_NONE) {
                
// ABS Label 420
if(thisline->length < 0)  {
	report_label_coverage("ABS", 420);
}

// ABS Label 421
if(stdout < 0)  {
	report_label_coverage("ABS", 421);
}
fwrite_unlocked(thisline->buffer, sizeof(char), thisline->length, stdout);
                do {
                    struct linebuffer *_tmp;
                    _tmp = (prevline);
                    (prevline) = (thisline);
                    (thisline) = _tmp;
                } while (0);;
                prevfield = thisfield;
                prevlen = thislen;
                first_group_printed = 1;
            }
        }
    };

      
// COR Label 422
if(((grouping == GM_BOTH || grouping == GM_APPEND) || first_group_printed) != ((grouping == GM_BOTH || grouping == GM_APPEND) && first_group_printed))  {
	report_label_coverage("COR", 422);
}

// MCC Label 423
if(( grouping == GM_BOTH && grouping == GM_APPEND ) && first_group_printed ) {
	report_label_coverage("MCC", 423);
}
// MCC Label 424
if(( grouping == GM_BOTH && grouping == GM_APPEND ) && !(first_group_printed) ) {
	report_label_coverage("MCC", 424);
}
// MCC Label 425
if(( grouping == GM_BOTH && !(grouping == GM_APPEND) ) && first_group_printed ) {
	report_label_coverage("MCC", 425);
}
// MCC Label 426
if(( grouping == GM_BOTH && !(grouping == GM_APPEND) ) && !(first_group_printed) ) {
	report_label_coverage("MCC", 426);
}
// MCC Label 427
if(( !(grouping == GM_BOTH) && grouping == GM_APPEND ) && first_group_printed ) {
	report_label_coverage("MCC", 427);
}
// MCC Label 428
if(( !(grouping == GM_BOTH) && grouping == GM_APPEND ) && !(first_group_printed) ) {
	report_label_coverage("MCC", 428);
}
// MCC Label 429
if(( !(grouping == GM_BOTH) && !(grouping == GM_APPEND) ) && first_group_printed ) {
	report_label_coverage("MCC", 429);
}
// MCC Label 430
if(( !(grouping == GM_BOTH) && !(grouping == GM_APPEND) ) && !(first_group_printed) ) {
	report_label_coverage("MCC", 430);
}
if ((grouping == GM_BOTH || grouping == GM_APPEND) && first_group_printed)
        putchar (delimiter);
    }
  else
    {
      char *prevfield;
      size_t prevlen;
      uintmax_t match_count = 0;
      bool first_delimiter = true;

      {
    struct linebuffer *temp_1 = readlinebuffer_delim(prevline, stdin, delimiter);
    
// ABS Label 432
if(temp_1 < 0)  {
	report_label_coverage("ABS", 432);
}

// ROR Label 433
if((temp_1 != 0) != (temp_1 == 0))  {
	report_label_coverage("ROR", 433);
}
if (temp_1 == 0)
        goto closefiles;
}
;
      prevfield = find_field (prevline);
      prevlen = prevline->length - 1 - (prevfield - prevline->buffer);

      while (1)
    {
        {
            int temp_1 = !(!feof_unlocked(stdin));
            
// ABS Label 434
if(temp_1 < 0)  {
	report_label_coverage("ABS", 434);
}
if (temp_1)
                break;
        }
        {
            _Bool match;
            char *thisfield;
            size_t thislen;
            {
                struct linebuffer *temp_3 = readlinebuffer_delim(thisline, stdin, delimiter);
                
// ABS Label 435
if(temp_3 < 0)  {
	report_label_coverage("ABS", 435);
}

// ROR Label 436
if((temp_3 != 0) != (temp_3 == 0))  {
	report_label_coverage("ROR", 436);
}
if (temp_3 == 0) {
                    {
                        int temp_2 = ferror_unlocked(stdin);
                        
// ABS Label 437
if(temp_2 < 0)  {
	report_label_coverage("ABS", 437);
}
if (temp_2)
                            goto closefiles;
                    }
                    break;
                }
            }
            thisfield = find_field(thisline);
            thislen = thisline->length - 1 - (thisfield - thisline->buffer);
            match = !different(thisfield, prevfield, thislen, prevlen);
            match_count += match;
            
// ABS Label 438
if(match_count < 0)  {
	report_label_coverage("ABS", 438);
}

// ROR Label 439
if((match_count != (18446744073709551615UL)) != (match_count == (18446744073709551615UL)))  {
	report_label_coverage("ROR", 439);
}
if (match_count == (18446744073709551615UL)) {
                if (count_occurrences)
                    error(1, 0, gettext("too many repeated lines"));
                match_count--;
            }
            
// ROR Label 440
if((delimit_groups == DM_NONE) != (delimit_groups != DM_NONE))  {
	report_label_coverage("ROR", 440);
}
if (delimit_groups != DM_NONE) {
                if (!match) {
                    
// ABS Label 441
if(match_count < 0)  {
	report_label_coverage("ABS", 441);
}
if (match_count)
                        first_delimiter = 0;
                } else { 
// ABS Label 442
if(match_count < 0)  {
	report_label_coverage("ABS", 442);
}

// ROR Label 443
if((match_count != 1) != (match_count == 1))  {
	report_label_coverage("ROR", 443);
}
if (match_count == 1) {
                    
// COR Label 444
if(((delimit_groups == DM_PREPEND) && (delimit_groups == DM_SEPARATE && !first_delimiter)) != ((delimit_groups == DM_PREPEND) || (delimit_groups == DM_SEPARATE && !first_delimiter)))  {
	report_label_coverage("COR", 444);
}

// MCC Label 445
if(( delimit_groups == DM_PREPEND ) && ( delimit_groups == DM_SEPARATE && !first_delimiter ) ) {
	report_label_coverage("MCC", 445);
}
// MCC Label 446
if(( delimit_groups == DM_PREPEND ) && ( delimit_groups == DM_SEPARATE && !(!first_delimiter) ) ) {
	report_label_coverage("MCC", 446);
}
// MCC Label 447
if(( delimit_groups == DM_PREPEND ) && ( !(delimit_groups == DM_SEPARATE) && !first_delimiter ) ) {
	report_label_coverage("MCC", 447);
}
// MCC Label 448
if(( delimit_groups == DM_PREPEND ) && ( !(delimit_groups == DM_SEPARATE) && !(!first_delimiter) ) ) {
	report_label_coverage("MCC", 448);
}
// MCC Label 449
if(( !(delimit_groups == DM_PREPEND) ) && ( delimit_groups == DM_SEPARATE && !first_delimiter ) ) {
	report_label_coverage("MCC", 449);
}
// MCC Label 450
if(( !(delimit_groups == DM_PREPEND) ) && ( delimit_groups == DM_SEPARATE && !(!first_delimiter) ) ) {
	report_label_coverage("MCC", 450);
}
// MCC Label 451
if(( !(delimit_groups == DM_PREPEND) ) && ( !(delimit_groups == DM_SEPARATE) && !first_delimiter ) ) {
	report_label_coverage("MCC", 451);
}
// MCC Label 452
if(( !(delimit_groups == DM_PREPEND) ) && ( !(delimit_groups == DM_SEPARATE) && !(!first_delimiter) ) ) {
	report_label_coverage("MCC", 452);
}
if ((delimit_groups == DM_PREPEND) || (delimit_groups == DM_SEPARATE && !first_delimiter))
                        putchar_unlocked(delimiter);
                };}

            }
            
// COR Label 453
if((!match && output_later_repeated) != (!match || output_later_repeated))  {
	report_label_coverage("COR", 453);
}

// MCC Label 454
if(!match && output_later_repeated ) {
	report_label_coverage("MCC", 454);
}
// MCC Label 455
if(!match && !(output_later_repeated) ) {
	report_label_coverage("MCC", 455);
}
// MCC Label 456
if(!(!match) && output_later_repeated ) {
	report_label_coverage("MCC", 456);
}
// MCC Label 457
if(!(!match) && !(output_later_repeated) ) {
	report_label_coverage("MCC", 457);
}
if (!match || output_later_repeated) {
                
// ABS Label 458
if(match < 0)  {
	report_label_coverage("ABS", 458);
}

// ABS Label 459
if(match_count < 0)  {
	report_label_coverage("ABS", 459);
}
writeline(prevline, match, match_count);
                do {
                    struct linebuffer *_tmp;
                    _tmp = (prevline);
                    (prevline) = (thisline);
                    (thisline) = _tmp;
                } while (0);;
                prevfield = thisfield;
                prevlen = thislen;
                if (!match)
                    match_count = 0;
            }
        }
    };


      
// ABS Label 431
if(match_count < 0)  {
	report_label_coverage("ABS", 431);
}
writeline (prevline, false, match_count);
    }

 closefiles:
  {
    int temp_2 = ferror_unlocked(stdin);
    
// ABS Label 460
if(temp_2 < 0)  {
	report_label_coverage("ABS", 460);
}
if (temp_2)
        goto label_2;
    else {
        int temp_1 = rpl_fclose(stdin);
        
// ABS Label 461
if(temp_1 < 0)  {
	report_label_coverage("ABS", 461);
}

// ROR Label 462
if((temp_1 == 0) != (temp_1 != 0))  {
	report_label_coverage("ROR", 462);
}
if (temp_1 != 0)
          label_2:
            error(1, 0, gettext("error reading %s"), infile);
    }
}
;

  /* stdout is handled via the atexit-invoked close_stdout function.  */

  free (lb1.buffer);
  free (lb2.buffer);
}

enum Skip_field_option_type
  {
    SFO_NONE,
    SFO_OBSOLETE,
    SFO_NEW
  };



int
main (int argc, char **argv)
{
  	

int optc = 0;
  bool posixly_correct = (getenv ("POSIXLY_CORRECT") != NULL);
  enum Skip_field_option_type skip_field_option_type = SFO_NONE;
  int nfiles = 0;
  char const *file[2];
  char delimiter = '\n';	/* change with --zero-terminated, -z */
  bool output_option_used = false;   /* if true, one of -u/-d/-D/-c was used */

  file[0] = file[1] = "-";
  initialize_main (&argc, &argv);
  set_program_name (argv[0]);
  setlocale (LC_ALL, "");
  bindtextdomain (PACKAGE, LOCALEDIR);
  textdomain (PACKAGE);
  hard_LC_COLLATE = hard_locale (LC_COLLATE);

  atexit (close_stdout);

  skip_chars = 0;
  skip_fields = 0;
  check_chars = SIZE_MAX;
  output_unique = output_first_repeated = true;
  output_later_repeated = false;
  countmode = count_none;
  delimit_groups = DM_NONE;

  while (true)
    {
      /* Parse an operand with leading "+" as a file after "--" was
         seen; or if pedantic and a file was seen; or if not
         obsolete.  */

      
// ABS Label 466
if(optc < 0)  {
	report_label_coverage("ABS", 466);
}

// COR Label 467
if((optc == -1 && (posixly_correct && nfiles != 0)) != (optc == -1 || (posixly_correct && nfiles != 0)))  {
	report_label_coverage("COR", 467);
}

// ROR Label 468
if((optc != -1) != (optc == -1))  {
	report_label_coverage("ROR", 468);
}

// MCC Label 469
if(optc == -1 && ( posixly_correct && nfiles != 0 ) ) {
	report_label_coverage("MCC", 469);
}
// MCC Label 470
if(optc == -1 && ( posixly_correct && !(nfiles != 0) ) ) {
	report_label_coverage("MCC", 470);
}
// MCC Label 471
if(optc == -1 && ( !(posixly_correct) && nfiles != 0 ) ) {
	report_label_coverage("MCC", 471);
}
// MCC Label 472
if(optc == -1 && ( !(posixly_correct) && !(nfiles != 0) ) ) {
	report_label_coverage("MCC", 472);
}
// MCC Label 473
if(!(optc == -1) && ( posixly_correct && nfiles != 0 ) ) {
	report_label_coverage("MCC", 473);
}
// MCC Label 474
if(!(optc == -1) && ( posixly_correct && !(nfiles != 0) ) ) {
	report_label_coverage("MCC", 474);
}
// MCC Label 475
if(!(optc == -1) && ( !(posixly_correct) && nfiles != 0 ) ) {
	report_label_coverage("MCC", 475);
}
// MCC Label 476
if(!(optc == -1) && ( !(posixly_correct) && !(nfiles != 0) ) ) {
	report_label_coverage("MCC", 476);
}
if (optc == -1 || (posixly_correct && nfiles != 0))
    goto label_3;
else {
    int temp_1 = getopt_long(argc, argv, "-0123456789Dcdf:is:uw:z", longopts, ((void *)0));
    int temp_2 = -1;
    if (((optc = temp_1) == temp_2))
      label_3:
        {
            
// ABS Label 477
if(argc < 0)  {
	report_label_coverage("ABS", 477);
}
// ABS Label 478
if(optind < 0)  {
	report_label_coverage("ABS", 478);
}

// ROR Label 479
if((argc < optind) != (argc <= optind))  {
	report_label_coverage("ROR", 479);
}
// ROR Label 480
if((argc > optind) != (argc <= optind))  {
	report_label_coverage("ROR", 480);
}
// ROR Label 481
if((argc >= optind) != (argc <= optind))  {
	report_label_coverage("ROR", 481);
}
if (argc <= optind)
                break;
            
// ABS Label 482
if(nfiles < 0)  {
	report_label_coverage("ABS", 482);
}

// ROR Label 483
if((nfiles != 2) != (nfiles == 2))  {
	report_label_coverage("ROR", 483);
}
if (nfiles == 2) {
                error(0, 0, gettext("extra operand %s"), quote(argv[optind]));
                usage(1);
            }
            file[nfiles++] = argv[optind++];
        }
    else
        switch (optc) {
          case 1:
            {
                unsigned long size;
                if (optarg[0] == '+' && posix2_version() < 200112 && xstrtoul(optarg, ((void *)0), 10, &size, "") == LONGINT_OK && size <= (18446744073709551615UL))
                    skip_chars = size;
                else { 
// ABS Label 484
if(nfiles < 0)  {
	report_label_coverage("ABS", 484);
}

// ROR Label 485
if((nfiles != 2) != (nfiles == 2))  {
	report_label_coverage("ROR", 485);
}
if (nfiles == 2) {
                    error(0, 0, gettext("extra operand %s"), quote(optarg));
                    usage(1);
                } else
                    file[nfiles++] = optarg;}
;
            }
            break;
          case '0':
          case '1':
          case '2':
          case '3':
          case '4':
          case '5':
          case '6':
          case '7':
          case '8':
          case '9':
            {
                
// ROR Label 486
if((skip_field_option_type != SFO_NEW) != (skip_field_option_type == SFO_NEW))  {
	report_label_coverage("ROR", 486);
}
if (skip_field_option_type == SFO_NEW)
              skip_fields = 0;

            if (!DECIMAL_DIGIT_ACCUMULATE (skip_fields, optc - '0', size_t))
              skip_fields = SIZE_MAX;

            skip_field_option_type = SFO_OBSOLETE;
            }
            break;
          case 'c':
            countmode = count_occurrences;
            output_option_used = 1;
            break;
          case 'd':
            output_unique = 0;
            output_option_used = 1;
            break;
          case 'D':
            output_unique = 0;
            output_later_repeated = 1;
            
// ABS Label 487
if(optarg < 0)  {
	report_label_coverage("ABS", 487);
}

// ROR Label 488
if((optarg != ((void *)0)) != (optarg == ((void *)0)))  {
	report_label_coverage("ROR", 488);
}
if (optarg == ((void *)0))
                delimit_groups = DM_NONE;
            else
                delimit_groups = ((delimit_method_map)[__xargmatch_internal("--all-repeated", optarg, delimit_method_string, (const char *)(delimit_method_map), sizeof *(delimit_method_map), argmatch_die)]);
            output_option_used = 1;
            break;
          case GROUP_OPTION:
            
// ABS Label 489
if(optarg < 0)  {
	report_label_coverage("ABS", 489);
}

// ROR Label 490
if((optarg != ((void *)0)) != (optarg == ((void *)0)))  {
	report_label_coverage("ROR", 490);
}
if (optarg == ((void *)0))
                grouping = GM_SEPARATE;
            else
                grouping = ((grouping_method_map)[__xargmatch_internal("--group", optarg, grouping_method_string, (const char *)(grouping_method_map), sizeof *(grouping_method_map), argmatch_die)]);
            break;
          case 'f':
            skip_field_option_type = SFO_NEW;
            skip_fields = size_opt(optarg, "invalid number of fields to skip");
            break;
          case 'i':
            ignore_case = 1;
            break;
          case 's':
            skip_chars = size_opt(optarg, "invalid number of bytes to skip");
            break;
          case 'u':
            output_first_repeated = 0;
            output_option_used = 1;
            break;
          case 'w':
            check_chars = size_opt(optarg, "invalid number of bytes to compare");
            break;
          case 'z':
            delimiter = '\x00';
            break;
          case GETOPT_HELP_CHAR:
            usage(0);
            break;
            ;
          case GETOPT_VERSION_CHAR:
            version_etc(stdout, "uniq", "GNU coreutils", Version, ("Richard M. Stallman"), ("David MacKenzie"), (char *)((void *)0));
            exit(0);
            break;
            ;
          default:
            usage(1);
        }
}

    };

  /* Note we could allow --group with -D at least, and that would
     avoid the need to specify a grouping method to --all-repeated.
     It was thought best to avoid deprecating those parameters though
     and keep --group separate to other options.  */
  
// COR Label 491
if((grouping != GM_NONE || output_option_used) != (grouping != GM_NONE && output_option_used))  {
	report_label_coverage("COR", 491);
}

// ROR Label 492
if((grouping == GM_NONE) != (grouping != GM_NONE))  {
	report_label_coverage("ROR", 492);
}

// MCC Label 493
if(grouping != GM_NONE && output_option_used ) {
	report_label_coverage("MCC", 493);
}
// MCC Label 494
if(grouping != GM_NONE && !(output_option_used) ) {
	report_label_coverage("MCC", 494);
}
// MCC Label 495
if(!(grouping != GM_NONE) && output_option_used ) {
	report_label_coverage("MCC", 495);
}
// MCC Label 496
if(!(grouping != GM_NONE) && !(output_option_used) ) {
	report_label_coverage("MCC", 496);
}
if (grouping != GM_NONE && output_option_used)
    {
      error (0, 0, _("--group is mutually exclusive with -c/-d/-D/-u"));
      usage (EXIT_FAILURE);
    }

  
// COR Label 497
if((grouping != GM_NONE || countmode != count_none) != (grouping != GM_NONE && countmode != count_none))  {
	report_label_coverage("COR", 497);
}

// ROR Label 498
if((grouping == GM_NONE) != (grouping != GM_NONE))  {
	report_label_coverage("ROR", 498);
}
// ROR Label 499
if((countmode == count_none) != (countmode != count_none))  {
	report_label_coverage("ROR", 499);
}

// MCC Label 500
if(grouping != GM_NONE && countmode != count_none ) {
	report_label_coverage("MCC", 500);
}
// MCC Label 501
if(grouping != GM_NONE && !(countmode != count_none) ) {
	report_label_coverage("MCC", 501);
}
// MCC Label 502
if(!(grouping != GM_NONE) && countmode != count_none ) {
	report_label_coverage("MCC", 502);
}
// MCC Label 503
if(!(grouping != GM_NONE) && !(countmode != count_none) ) {
	report_label_coverage("MCC", 503);
}
if (grouping != GM_NONE && countmode != count_none)
    {
      error (0, 0,
           _("grouping and printing repeat counts is meaningless"));
      usage (EXIT_FAILURE);
    }

  
// COR Label 504
if((countmode == count_occurrences || output_later_repeated) != (countmode == count_occurrences && output_later_repeated))  {
	report_label_coverage("COR", 504);
}

// ROR Label 505
if((countmode != count_occurrences) != (countmode == count_occurrences))  {
	report_label_coverage("ROR", 505);
}

// MCC Label 506
if(countmode == count_occurrences && output_later_repeated ) {
	report_label_coverage("MCC", 506);
}
// MCC Label 507
if(countmode == count_occurrences && !(output_later_repeated) ) {
	report_label_coverage("MCC", 507);
}
// MCC Label 508
if(!(countmode == count_occurrences) && output_later_repeated ) {
	report_label_coverage("MCC", 508);
}
// MCC Label 509
if(!(countmode == count_occurrences) && !(output_later_repeated) ) {
	report_label_coverage("MCC", 509);
}
if (countmode == count_occurrences && output_later_repeated)
    {
      error (0, 0,
           _("printing all duplicated lines and repeat counts is meaningless"));
      usage (EXIT_FAILURE);
    }

  
// ABS Label 463
if(file[0] < 0)  {
	report_label_coverage("ABS", 463);
}

// ABS Label 464
if(file[1] < 0)  {
	report_label_coverage("ABS", 464);
}

// ABS Label 465
if(delimiter < 0)  {
	report_label_coverage("ABS", 465);
}
check_file (file[0], file[1], delimiter);

  	
return EXIT_SUCCESS;
}
